id: P000638
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3868
  title: ངག་དབང་བཟང་པོའི་རྣམ་ཐར་གྱི་ཆ་ཤས་བརྗོད་པ་ཟླ་ཚེས་བདུད་རྩིའི་འཛུམ་རླབས་
  author: ''
  volumes:
    a0be6a2c98f04f678688066150c578e7:
      image_group_id: I1KG3947
      title: ''
      volume_number: 1
      total_pages: 64
