id: I9BE72E84
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T14:31:28+00:00'
last_modified: '2022-06-07T12:31:50.772872+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3868
  title: ངག་དབང་བཟང་པོའི་རྣམ་ཐར་གྱི་ཆ་ཤས་བརྗོད་པ་ཟླ་ཚེས་བདུད་རྩིའི་འཛུམ་རླབས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2625':
      image_group_id: I1KG3947
      title: ''
      total_pages: 64
      order: 1
      base_file: 2625.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
